# Generated by Django 4.2 on 2023-04-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='abcdef', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
